[[config.copier-client-config]]
repo = "DominikKirst/copier-client-config"
url = "git@github.com:DominikKirst/copier-client-config.git"
branch = "develop"

[[lib.copier-client-lib]]
repo = "DominikKirst/copier-client-lib"
url = "git@github.com:DominikKirst/copier-client-lib.git"
branch = "develop"

[[lib.copier-client-lib-pr]]
repo = "DominikKirst/copier-client-lib-pr"
url = "git@github.com:DominikKirst/copier-client-lib-pr.git"
branch = "develop"
sync.type = "pr"
sync.automerge = "true"

[[lib.copier-client-lib-event]]
repo = "DominikKirst/copier-client-lib-event"
url = "git@github.com:DominikKirst/copier-client-lib-event.git"
branch = "develop"
sync.type = "event"

[[deployable.copier-client-deployable]]
repo = "DominikKirst/copier-client-deployable"
url = "git@github.com:DominikKirst/copier-client-deployable.git"
branch = "develop"
