name: Sync (dry-run)

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  fanout:
    uses: ./.github/workflows/fanout.yml
    secrets: inherit
    with:
      base_sha: ${{ github.event.pull_request.base.sha }}
      dry_run: true
      vcs_ref: ${{ github.event.pull_request.head.sha }}
      pr_number: ${{ github.event.pull_request.number }}
