name: Sync

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      url:
        required: true
        type: string
      branch:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean
      type:
        required: true
        type: string

jobs:
  sync:
    name: ${{ inputs.dry_run && format('{0} (dry-run)', inputs.repo) || format('{0} sync', inputs.repo) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          dest="${{ inputs.repo }}"
          dest="${dest##*/}"
          pretend="${{ inputs.dry_run && ' --pretend' || '' }}"
          echo "git clone --branch ${{ inputs.branch }} ${{ inputs.url }} ${dest}"
          echo "cd ${dest}"
          echo "copier update --trust --defaults --skip-answered --vcs-ref ${{ github.sha }} -d type=${{ inputs.type }}${pretend}"
