name: Sync

on:
  workflow_call:
    inputs:
      repo:
        required: true
        type: string
      url:
        required: true
        type: string
      branch:
        required: true
        type: string
      dry_run:
        required: true
        type: boolean

jobs:
  sync:
    name: ${{ inputs.dry_run && format('{0} (dry-run)', inputs.repo) || format('{0} sync', inputs.repo) }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "copier sync${{ inputs.dry_run && ' --dry-run' || '' }}"
          echo "repo: ${{ inputs.repo }}"
          echo "url: ${{ inputs.url }}"
          echo "branch: ${{ inputs.branch }}"
